export const SEND_MESSAGE_REQUEST = '@@chat/SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = '@@chat/SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILURE = '@@chat/SEND_MESSAGE_FAILURE'

export const GET_PROFILE_INFO_REQUEST = '@@profile/GET_PROFILE_INFO_REQUEST'
export const GET_PROFILE_INFO_SUCCESS = '@@profile/GET_PROFILE_INFO_SUCCESS'
export const GET_PROFILE_INFO_FAILURE = '@@profile/GET_PROFILE_INFO_FAILURE'

export const GET_CHATS_LIST_REQUEST = '@@chats/GET_CHATS_LIST_REQUEST'
export const GET_CHATS_LIST_SUCCESS = '@@chats/GET_CHATS_LIST_SUCCESS'
export const GET_CHATS_LIST_FAILURE = '@@chats/GET_CHATS_LIST_FAILURE'

export const GET_MESSAGES_LIST_REQUEST = '@@chat/GET_MESSAGES_LIST_REQUEST'
export const GET_MESSAGES_LIST_SUCCESS = '@@chat/GET_MESSAGES_LIST_SUCCESS'
export const GET_MESSAGES_LIST_FAILURE = '@@chat/GET_MESSAGES_LIST_FAILURE'

export const GET_MESSAGE_SUCCESS = '@@chat/GET_MESSAGE_SUCCESS'
export const SOCKET_DISCONNECTED = '@@chat/SOCKET_DISCONNECTED'

export const CREATE_NEW_CHAT_REQUEST = '@@chats/CREATE_NEW_CHAT_REQUEST'
export const CREATE_NEW_CHAT_SUCCESS = '@@chats/CREATE_NEW_CHAT_SUCCESS'
export const CREATE_NEW_CHAT_FAILURE = '@@chats/CREATE_NEW_CHAT_FAILURE'

export const GET_GLOBAL_REQUEST = '@@global/GET_GLOBAL_REQUEST'
export const GET_GLOBAL_SUCCESS = '@@global/GET_GLOBAL_SUCCESS'
export const GET_GLOBAL_FAILURE = '@@global/GET_GLOBAL_FAILURE'

export const SET_EMOJI = '@@emoji/SET_EMOJI'
export const CLEAR_EMOJI = '@@emoji/CLEAR_EMOJI'

export const GET_CENT_TOKEN_REQUEST = '@@centrifugo/GET_CENT_TOKEN_REQUEST'
export const GET_CENT_TOKEN_SUCCESS = '@@centrifugo/GET_CENT_TOKEN_SUCCESS'
export const GET_CENT_TOKEN_FAILURE = '@@centrifugo/GET_CENT TOKEN_FAILURE'

export const SET_RTC_UID_SUCCESS = '@@rtc/SET_RTC_UID_SUCCESS'
export const GET_RTC_MESSAGE_SUCCESS = '@@rtc/GET_RTC_MESSAGE_SUCCESS'
export const RTC_CONNECT_SUCCESS = '@@rtc/RTC_CONNECT_SUCCESS'
export const RTC_DISCONNECT_SUCCESS = '@@rtc/RTC_DISCONNECT_SUCCESS'
export const RTC_CONNECT_FAILURE = '@@rtc/RRTC_CONNECT_FAILURE'
