export const GET_WEATHER_REQUEST = '@@location/GET_WEATHER_REQUEST'
export const GET_WEATHER_SUCCESS = '@@location/GET_WEATHER_SUCCESS'
export const GET_WEATHER_FAILURE = '@@location/GET_WEATHER_FAILURE'

export const GET_GLOBAL_REQUEST = '@@global/GET_GLOBAL_REQUEST'
export const GET_GLOBAL_SUCCESS = '@@global/GET_GLOBAL_SUCCESS'
export const GET_GLOBAL_FAILURE = '@@global/GET_GLOBAL_FAILURE'

export const GET_WEATHER_BY_COORDS_REQUEST = '@@location/GET_WEATHER_BY_COORDS_REQUEST'
export const GET_WEATHER_BY_COORDS_SUCCESS = '@@location/GET_WEATHER_BY_COORDS_SUCCESS'
export const GET_WEATHER_BY_COORDS_FAILURE = '@@location/GET_WEATHER_BY_COORDS_FAILURE'
