export const GET_WEATHER_REQUEST = '@@location/GET_WEATHER_REQUEST'
export const GET_WEATHER_SUCCESS = '@@location/GET_WEATHER_SUCCESS'
export const GET_WEATHER_FAILURE = '@@location/GET_WEATHER_FAILURE'

export const CHANGE_GLOBAL_REQUEST = '@@global/GET_GLOBAL_REQUEST'
export const CHANGE_GLOBAL_SUCCESS = '@@global/GET_GLOBAL_SUCCESS'
export const CHANGE_GLOBAL_FAILURE = '@@global/GET_GLOBAL_FAILURE'

export const CHANGE_COORDS_REQUEST = '@@global/GET_COORDS_REQUEST'
export const CHANGE_COORDS_SUCCESS = '@@global/GET_COORDS_SUCCESS'
export const CHANGE_COORDS_FAILURE = '@@global/GET_COORDS_FAILURE'

export const GET_FORECAST_WEATHER_REQUEST = '@@weather/GET_FORECAST_WEATHER_REQUEST'
export const GET_FORECAST_WEATHER_SUCCESS = '@@weather/GET_FORECAST_WEATHER_SUCCESS'
export const GET_FORECAST_WEATHER_FAILURE = '@@weather/GET_FORECAST_WEATHER_FAILURE'
